[package]
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
name = "shady"
version = "0.1.0"

[dependencies]
clap = "2.10.4"
glium = "0.15.0"
notify = "2.6.3"

[dependencies.shady-script]
path = "shady-script"
