use ::ast;
use ::image::ImageDefinition;

grammar;

pub ImageDefinition: ImageDefinition = "image()" <Block> => ImageDefinition(<>);

pub Block: ast::Block = "{" <Stmt*> "}" => ast::Block(<>);

pub Stmt: ast::Stmt = {
    "return" <Expr> => ast::ret(<>)
};

pub Expr: ast::Expr = {
    r"[0-9]+(\.[0-9]+)?" => ast::lit(<>),
    "(" <Expr> "," <Expr> ")" => ast::vec2(<>),
    "(" <Expr> "," <Expr> "," <Expr> ")" => ast::vec3(<>),
};
